version: '3.9'

services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - mg1-tenant

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - mg1-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - mg1-tenant
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    restart: always

  mg-hapi-test1:
    build:
      context: .
      target: development
    ports:
      - '3000:3000'
      - '9229:9229'
    links:
      - 'localstack:localstack'
      - 'mongodb:mongodb'
    depends_on:
      localstack:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3000
      PORT_DEBUG: 9229
      NODE_ENV: development
      LOCALSTACK_ENDPOINT: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/
    networks:
      - mg1-tenant
    command: npm run docker:dev
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
      #- ./src:/home/node/src
      #- ./package.json:/home/node/package.json

################################################################################

volumes:
  mongodb-data:

networks:
  mg1-tenant:
    driver: bridge
    name: mg1-tenant
